import java.util.*;

public class CoordinatePrintTaskDataAnnotation {

    static class Entry {
        int x;
        int y;
        char ch;

        Entry(int x, int y, char ch) {
            this.x = x;
            this.y = y;
            this.ch = ch;
        }
    }

    public static void main(String[] args) {

        List<Entry> entries = new ArrayList<>();
        entries.add(new Entry(87, 0, '░'));
        entries.add(new Entry(78, 3, '█'));
        entries.add(new Entry(28, 2, '░'));
        entries.add(new Entry(26, 2, '█'));
        entries.add(new Entry(9, 1, '█'));
        entries.add(new Entry(48, 2, '░'));
        entries.add(new Entry(31, 5, '░'));
        entries.add(new Entry(48, 0, '█'));
        entries.add(new Entry(27, 0, '░'));
        entries.add(new Entry(48, 4, '░'));
        entries.add(new Entry(15, 4, '░'));
        entries.add(new Entry(74, 1, '█'));
        entries.add(new Entry(35, 2, '█'));
        entries.add(new Entry(71, 0, '█'));
        entries.add(new Entry(61, 5, '█'));
        entries.add(new Entry(35, 3, '█'));
        entries.add(new Entry(67, 4, '░'));
        entries.add(new Entry(63, 4, '░'));
        entries.add(new Entry(41, 1, '░'));
        entries.add(new Entry(73, 5, '█'));
        entries.add(new Entry(40, 2, '█'));
        entries.add(new Entry(67, 0, '█'));
        entries.add(new Entry(32, 4, '░'));
        entries.add(new Entry(39, 4, '░'));
        entries.add(new Entry(65, 6, '█'));
        entries.add(new Entry(60, 6, '░'));
        entries.add(new Entry(49, 0, '█'));
        entries.add(new Entry(40, 0, '█'));
        entries.add(new Entry(46, 1, '█'));
        entries.add(new Entry(79, 1, '█'));
        entries.add(new Entry(66, 6, '█'));
        entries.add(new Entry(87, 4, '█'));
        entries.add(new Entry(72, 6, '█'));
        entries.add(new Entry(56, 6, '█'));
        entries.add(new Entry(73, 2, '█'));
        entries.add(new Entry(8, 6, '█'));
        entries.add(new Entry(14, 3, '░'));
        entries.add(new Entry(79, 5, '█'));
        entries.add(new Entry(8, 5, '█'));
        entries.add(new Entry(60, 0, '░'));
        entries.add(new Entry(82, 0, '█'));
        entries.add(new Entry(54, 5, '░'));
        entries.add(new Entry(54, 0, '█'));
        entries.add(new Entry(79, 2, '░'));
        entries.add(new Entry(66, 2, '█'));
        entries.add(new Entry(61, 2, '█'));
        entries.add(new Entry(38, 2, '█'));
        entries.add(new Entry(44, 0, '█'));
        entries.add(new Entry(35, 1, '░'));
        entries.add(new Entry(88, 5, '█'));
        entries.add(new Entry(84, 6, '█'));
        entries.add(new Entry(8, 1, '█'));
        entries.add(new Entry(78, 1, '█'));
        entries.add(new Entry(28, 4, '█'));
        entries.add(new Entry(52, 5, '█'));
        entries.add(new Entry(75, 5, '░'));
        entries.add(new Entry(49, 6, '█'));
        entries.add(new Entry(15, 0, '█'));
        entries.add(new Entry(13, 1, '█'));
        entries.add(new Entry(0, 0, '█'));
        entries.add(new Entry(78, 2, '█'));
        entries.add(new Entry(41, 0, '█'));
        entries.add(new Entry(10, 4, '░'));
        entries.add(new Entry(1, 0, '█'));
        entries.add(new Entry(83, 0, '█'));
        entries.add(new Entry(46, 2, '█'));
        entries.add(new Entry(73, 1, '█'));
        entries.add(new Entry(77, 4, '█'));
        entries.add(new Entry(77, 1, '█'));
        entries.add(new Entry(26, 3, '█'));
        entries.add(new Entry(47, 4, '█'));
        entries.add(new Entry(73, 0, '░'));
        entries.add(new Entry(27, 3, '█'));
        entries.add(new Entry(79, 4, '░'));
        entries.add(new Entry(12, 2, '█'));
        entries.add(new Entry(89, 1, '░'));
        entries.add(new Entry(68, 0, '█'));
        entries.add(new Entry(1, 6, '█'));
        entries.add(new Entry(74, 2, '█'));
        entries.add(new Entry(61, 4, '█'));
        entries.add(new Entry(89, 5, '░'));
        entries.add(new Entry(46, 6, '█'));
        entries.add(new Entry(27, 1, '█'));
        entries.add(new Entry(27, 4, '█'));
        entries.add(new Entry(77, 5, '█'));
        entries.add(new Entry(80, 0, '█'));
        entries.add(new Entry(0, 2, '█'));
        entries.add(new Entry(13, 5, '█'));
        entries.add(new Entry(2, 5, '░'));
        entries.add(new Entry(65, 0, '█'));
        entries.add(new Entry(39, 3, '█'));
        entries.add(new Entry(69, 6, '█'));
        entries.add(new Entry(10, 6, '░'));
        entries.add(new Entry(46, 0, '█'));
        entries.add(new Entry(73, 6, '░'));
        entries.add(new Entry(27, 5, '█'));
        entries.add(new Entry(36, 4, '░'));
        entries.add(new Entry(47, 5, '█'));
        entries.add(new Entry(16, 6, '█'));
        entries.add(new Entry(22, 0, '░'));
        entries.add(new Entry(85, 0, '█'));
        entries.add(new Entry(33, 2, '█'));
        entries.add(new Entry(37, 4, '█'));
        entries.add(new Entry(54, 6, '█'));
        entries.add(new Entry(18, 0, '█'));
        entries.add(new Entry(28, 5, '█'));
        entries.add(new Entry(31, 2, '█'));
        entries.add(new Entry(39, 1, '█'));
        entries.add(new Entry(7, 3, '█'));
        entries.add(new Entry(38, 4, '█'));
        entries.add(new Entry(1, 1, '█'));
        entries.add(new Entry(42, 0, '░'));
        entries.add(new Entry(83, 6, '█'));
        entries.add(new Entry(40, 1, '█'));
        entries.add(new Entry(53, 5, '█'));
        entries.add(new Entry(70, 6, '█'));
        entries.add(new Entry(21, 0, '█'));
        entries.add(new Entry(65, 2, '█'));
        entries.add(new Entry(10, 2, '░'));
        entries.add(new Entry(80, 1, '░'));
        entries.add(new Entry(87, 5, '█'));
        entries.add(new Entry(0, 5, '█'));
        entries.add(new Entry(10, 3, '░'));
        entries.add(new Entry(38, 3, '█'));
        entries.add(new Entry(55, 6, '█'));
        entries.add(new Entry(30, 4, '█'));
        entries.add(new Entry(67, 5, '░'));
        entries.add(new Entry(48, 6, '█'));
        entries.add(new Entry(19, 0, '█'));
        entries.add(new Entry(2, 0, '░'));
        entries.add(new Entry(38, 6, '░'));
        entries.add(new Entry(15, 1, '█'));
        entries.add(new Entry(84, 0, '█'));
        entries.add(new Entry(62, 4, '█'));
        entries.add(new Entry(0, 4, '█'));
        entries.add(new Entry(67, 3, '█'));
        entries.add(new Entry(0, 1, '█'));
        entries.add(new Entry(74, 5, '█'));
        entries.add(new Entry(37, 5, '█'));
        entries.add(new Entry(38, 5, '█'));
        entries.add(new Entry(53, 1, '█'));
        entries.add(new Entry(62, 1, '░'));
        entries.add(new Entry(14, 5, '█'));
        entries.add(new Entry(88, 1, '█'));
        entries.add(new Entry(29, 6, '█'));
        entries.add(new Entry(86, 6, '█'));
        entries.add(new Entry(47, 2, '█'));
        entries.add(new Entry(32, 3, '█'));
        entries.add(new Entry(62, 2, '█'));
        entries.add(new Entry(25, 1, '█'));
        entries.add(new Entry(34, 4, '█'));
        entries.add(new Entry(8, 2, '█'));
        entries.add(new Entry(26, 0, '█'));
        entries.add(new Entry(36, 2, '░'));
        entries.add(new Entry(79, 3, '░'));
        entries.add(new Entry(33, 1, '█'));
        entries.add(new Entry(6, 3, '█'));
        entries.add(new Entry(80, 6, '█'));
        entries.add(new Entry(8, 0, '█'));
        entries.add(new Entry(65, 5, '█'));
        entries.add(new Entry(58, 6, '█'));
        entries.add(new Entry(63, 2, '░'));
        entries.add(new Entry(54, 4, '░'));
        entries.add(new Entry(27, 2, '█'));
        entries.add(new Entry(46, 5, '█'));
        entries.add(new Entry(4, 3, '█'));
        entries.add(new Entry(20, 6, '█'));
        entries.add(new Entry(86, 5, '█'));
        entries.add(new Entry(56, 0, '█'));
        entries.add(new Entry(22, 1, '█'));
        entries.add(new Entry(28, 6, '█'));
        entries.add(new Entry(8, 4, '█'));
        entries.add(new Entry(5, 3, '█'));
        entries.add(new Entry(53, 3, '█'));
        entries.add(new Entry(73, 4, '█'));
        entries.add(new Entry(29, 3, '░'));
        entries.add(new Entry(35, 5, '█'));
        entries.add(new Entry(55, 0, '█'));
        entries.add(new Entry(16, 5, '░'));
        entries.add(new Entry(36, 6, '█'));
        entries.add(new Entry(87, 3, '█'));
        entries.add(new Entry(37, 6, '█'));
        entries.add(new Entry(80, 5, '░'));
        entries.add(new Entry(61, 3, '█'));
        entries.add(new Entry(75, 4, '░'));
        entries.add(new Entry(34, 3, '█'));
        entries.add(new Entry(17, 0, '█'));
        entries.add(new Entry(70, 3, '█'));
        entries.add(new Entry(30, 5, '█'));
        entries.add(new Entry(59, 6, '█'));
        entries.add(new Entry(21, 5, '█'));
        entries.add(new Entry(28, 3, '█'));
        entries.add(new Entry(21, 1, '█'));
        entries.add(new Entry(19, 6, '█'));
        entries.add(new Entry(52, 4, '█'));
        entries.add(new Entry(65, 4, '█'));
        entries.add(new Entry(45, 0, '█'));
        entries.add(new Entry(23, 5, '░'));
        entries.add(new Entry(85, 6, '█'));
        entries.add(new Entry(1, 2, '█'));
        entries.add(new Entry(66, 3, '█'));
        entries.add(new Entry(86, 1, '█'));
        entries.add(new Entry(59, 0, '█'));
        entries.add(new Entry(52, 6, '█'));
        entries.add(new Entry(63, 3, '░'));
        entries.add(new Entry(22, 6, '░'));
        entries.add(new Entry(50, 6, '░'));
        entries.add(new Entry(69, 0, '█'));
        entries.add(new Entry(66, 0, '█'));
        entries.add(new Entry(88, 4, '█'));
        entries.add(new Entry(18, 6, '█'));
        entries.add(new Entry(31, 3, '█'));
        entries.add(new Entry(46, 3, '█'));
        entries.add(new Entry(10, 5, '░'));
        entries.add(new Entry(78, 5, '█'));
        entries.add(new Entry(66, 1, '█'));
        entries.add(new Entry(68, 3, '█'));
        entries.add(new Entry(17, 6, '█'));
        entries.add(new Entry(73, 3, '░'));
        entries.add(new Entry(89, 2, '░'));
        entries.add(new Entry(23, 1, '░'));
        entries.add(new Entry(89, 3, '░'));
        entries.add(new Entry(16, 1, '░'));
        entries.add(new Entry(36, 3, '░'));
        entries.add(new Entry(47, 1, '█'));
        entries.add(new Entry(58, 0, '█'));
        entries.add(new Entry(54, 1, '░'));
        entries.add(new Entry(66, 4, '█'));
        entries.add(new Entry(71, 6, '█'));
        entries.add(new Entry(35, 4, '█'));
        entries.add(new Entry(9, 6, '█'));
        entries.add(new Entry(67, 1, '░'));
        entries.add(new Entry(10, 0, '░'));
        entries.add(new Entry(32, 2, '█'));
        entries.add(new Entry(16, 0, '█'));
        entries.add(new Entry(13, 3, '█'));
        entries.add(new Entry(28, 1, '░'));
        entries.add(new Entry(50, 0, '░'));
        entries.add(new Entry(21, 6, '█'));
        entries.add(new Entry(9, 5, '█'));
        entries.add(new Entry(0, 3, '█'));
        entries.add(new Entry(68, 6, '█'));
        entries.add(new Entry(81, 6, '█'));
        entries.add(new Entry(0, 6, '█'));
        entries.add(new Entry(72, 0, '█'));
        entries.add(new Entry(52, 3, '█'));
        entries.add(new Entry(22, 5, '█'));
        entries.add(new Entry(62, 5, '░'));
        entries.add(new Entry(48, 3, '░'));
        entries.add(new Entry(74, 4, '█'));
        entries.add(new Entry(45, 6, '█'));
        entries.add(new Entry(87, 1, '█'));
        entries.add(new Entry(72, 3, '█'));
        entries.add(new Entry(47, 0, '█'));
        entries.add(new Entry(54, 3, '░'));
        entries.add(new Entry(34, 1, '█'));
        entries.add(new Entry(53, 4, '█'));
        entries.add(new Entry(65, 1, '█'));
        entries.add(new Entry(33, 3, '░'));
        entries.add(new Entry(20, 0, '█'));
        entries.add(new Entry(39, 5, '░'));
        entries.add(new Entry(36, 5, '█'));
        entries.add(new Entry(9, 0, '█'));
        entries.add(new Entry(57, 6, '█'));
        entries.add(new Entry(57, 0, '█'));
        entries.add(new Entry(46, 4, '█'));
        entries.add(new Entry(75, 2, '░'));
        entries.add(new Entry(15, 2, '░'));
        entries.add(new Entry(81, 0, '█'));
        entries.add(new Entry(77, 2, '█'));
        entries.add(new Entry(60, 1, '█'));
        entries.add(new Entry(78, 4, '█'));
        entries.add(new Entry(77, 3, '█'));
        entries.add(new Entry(44, 6, '█'));
        entries.add(new Entry(1, 4, '█'));
        entries.add(new Entry(14, 2, '█'));
        entries.add(new Entry(9, 3, '█'));
        entries.add(new Entry(14, 1, '█'));
        entries.add(new Entry(13, 4, '█'));
        entries.add(new Entry(48, 1, '░'));
        entries.add(new Entry(34, 2, '█'));
        entries.add(new Entry(87, 6, '░'));
        entries.add(new Entry(69, 3, '█'));
        entries.add(new Entry(75, 1, '░'));
        entries.add(new Entry(29, 5, '█'));
        entries.add(new Entry(3, 3, '█'));
        entries.add(new Entry(54, 2, '░'));
        entries.add(new Entry(60, 5, '█'));
        entries.add(new Entry(15, 6, '█'));
        entries.add(new Entry(79, 6, '█'));
        entries.add(new Entry(13, 2, '█'));
        entries.add(new Entry(87, 2, '█'));
        entries.add(new Entry(52, 1, '█'));
        entries.add(new Entry(2, 1, '░'));
        entries.add(new Entry(89, 4, '░'));
        entries.add(new Entry(65, 3, '█'));
        entries.add(new Entry(39, 2, '█'));
        entries.add(new Entry(29, 4, '░'));
        entries.add(new Entry(2, 2, '░'));
        entries.add(new Entry(26, 1, '█'));
        entries.add(new Entry(2, 3, '█'));
        entries.add(new Entry(8, 3, '█'));
        entries.add(new Entry(53, 2, '█'));
        entries.add(new Entry(1, 3, '█'));
        entries.add(new Entry(66, 5, '█'));
        entries.add(new Entry(30, 6, '░'));
        entries.add(new Entry(9, 2, '█'));
        entries.add(new Entry(71, 3, '█'));
        entries.add(new Entry(88, 2, '█'));
        entries.add(new Entry(10, 1, '░'));
        entries.add(new Entry(53, 6, '█'));
        entries.add(new Entry(2, 4, '░'));
        entries.add(new Entry(53, 0, '█'));
        entries.add(new Entry(47, 3, '█'));
        entries.add(new Entry(62, 3, '█'));
        entries.add(new Entry(15, 5, '█'));
        entries.add(new Entry(52, 2, '█'));
        entries.add(new Entry(25, 0, '█'));
        entries.add(new Entry(88, 3, '█'));
        entries.add(new Entry(47, 6, '█'));
        entries.add(new Entry(67, 2, '░'));
        entries.add(new Entry(86, 0, '█'));
        entries.add(new Entry(2, 6, '░'));
        entries.add(new Entry(32, 1, '█'));
        entries.add(new Entry(1, 5, '█'));
        entries.add(new Entry(40, 3, '░'));
        entries.add(new Entry(14, 4, '█'));
        entries.add(new Entry(61, 1, '█'));
        entries.add(new Entry(67, 6, '█'));
        entries.add(new Entry(31, 4, '█'));
        entries.add(new Entry(48, 5, '░'));
        entries.add(new Entry(70, 0, '█'));
        entries.add(new Entry(79, 0, '█'));
        entries.add(new Entry(52, 0, '█'));
        entries.add(new Entry(39, 0, '█'));
        entries.add(new Entry(82, 6, '█'));
        entries.add(new Entry(12, 3, '█'));
        entries.add(new Entry(9, 4, '█'));
        entries.add(new Entry(41, 2, '░'));
        entries.add(new Entry(12, 4, '█'));


        int maxX = 0;
        int maxY = 0;

        for (Entry e : entries) {
            maxX = Math.max(maxX, e.x);
            maxY = Math.max(maxY, e.y);
        }

        char[][] grid = new char[maxY + 1][maxX + 1];

        for (int i = 0; i <= maxY; i++) {
            Arrays.fill(grid[i], ' ');
        }

        for (Entry e : entries) {
            grid[e.y][e.x] = e.ch;
        }

        for (int i = 0; i <= maxY; i++) {
            for (int j = 0; j <= maxX; j++) {
                System.out.print(grid[i][j]);
            }
            System.out.println();
        }
    }
}
